create table if not exists public.exam_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  completed_at timestamptz not null default now(),
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  total_correct smallint not null check (total_correct between 0 and 60),
  total_questions smallint not null default 60 check (total_questions = 60),
  passed boolean not null,
  category_scores jsonb not null default '{}'::jsonb check (jsonb_typeof(category_scores) = 'object')
);

create index if not exists exam_attempts_user_completed_idx
on public.exam_attempts (user_id, completed_at desc);

alter table public.exam_attempts enable row level security;

revoke all on table public.exam_attempts from anon;
revoke update, delete on table public.exam_attempts from authenticated;
grant select, insert on table public.exam_attempts to authenticated;
grant usage, select on sequence public.exam_attempts_id_seq to authenticated;

drop policy if exists "Users can read their own exam attempts" on public.exam_attempts;
create policy "Users can read their own exam attempts"
on public.exam_attempts
for select
to authenticated
using (
  (select auth.uid()) = user_id
  and exists (
    select 1
    from public.user_access
    where user_access.user_id = (select auth.uid())
      and user_access.expires_at > now()
  )
);

drop policy if exists "Users can create their own exam attempts" on public.exam_attempts;
create policy "Users can create their own exam attempts"
on public.exam_attempts
for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1
    from public.user_access
    where user_access.user_id = (select auth.uid())
      and user_access.expires_at > now()
  )
);

